# -*- coding: utf-8 -*-
"""train_model_ml_zoompcamp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITFEFUUy8pt1HQpBWd01j1aeXfWnWtOe
"""

import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# --- Configuration ---
RANDOM_SEED = 42
MODEL_OUTPUT_FILE = 'model.bin'
BEST_RF_MAX_DEPTH = 10

# Load the data
def load_data(file_path='winequality-red.csv'):
    """Loads and preprocesses the wine quality dataset."""
    print("Loading data...")

    # Load the data
    df = pd.read_csv(file_path)

    # Standardize column names
    df.columns = df.columns.str.lower().str.replace(' ', '_')

    return df

def prepare_features_and_target(df):
    """Defines the target variable and separates features."""

    # Define the Binary Target Variable: 'good_quality'
    # Good quality is defined as a rating of 7 or higher.
    df['good_quality'] = (df['quality'] >= 7).astype(int)

    # Drop the original 'quality' score to avoid leakage
    df = df.drop(columns=['quality'])

    # Set Features (X) and Target (y)
    X = df.drop(columns=['good_quality'])
    y = df['good_quality']

    return X, y

def train_model(X_train_full, y_train_full, max_depth):
    """Trains the final selected model."""
    print(f"Training final Random Forest model with max_depth={max_depth}...")

    # Instantiate the final model with the optimal tuned parameter
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=max_depth,
        random_state=RANDOM_SEED,
        n_jobs=-1
    )

    # Fit the model on the full available training data
    model.fit(X_train_full, y_train_full)

    return model

def save_model(model, output_file):
    """Saves the fitted model using pickle."""
    print(f"Saving model to {output_file}...")
    with open(output_file, 'wb') as f_out:
        pickle.dump(model, f_out)

if __name__ == '__main__':
    # 1. Load and Prepare Data
    df = load_data()
    X, y = prepare_features_and_target(df)

    # 2. Since train.py is for final training, we use all data.
    X_train_full, y_train_full = X, y

    # 3. Train the Model
    final_model = train_model(X_train_full, y_train_full, BEST_RF_MAX_DEPTH)

    # 4. Save the Model
    save_model(final_model, MODEL_OUTPUT_FILE)
    print("Training script finished successfully.")

